/*

 TILES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char bkgdata[] =
{
  0x40,0x00,0x80,0x00,0x01,0x00,0x02,0x00,
  0x04,0x00,0x08,0x00,0x10,0x00,0x20,0x00,
  0x40,0x00,0x80,0x00,0x01,0x00,0x02,0x00,
  0x04,0x00,0x08,0x00,0x10,0x00,0x00,0xFF
};

unsigned char track[] =         /* display tile 1 from bkg */
{
  1, NULL
};

unsigned char borde[] =         /* display tile 2 from bkg */
{
  2, NULL
};

/* End of TILES.C */
